apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8481
      protocol: TCP
      name: http
  selector:
    app: api-server
