apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
